### ISSUE TITLE
What does "restoring super activation" really means?

### ISSUE THREAD

**Issue by fxmarty-amd** [mengxiayu/LLMSuperWeight#3]
Hi,

Say I have an input activation of size `(1, m)`, and I go through the operation `y = x @ W.T` with `W` of shape `(n, m)`.

I detect a super activation in `x` at position `(0, k)`, and in `y` at position `(0, j)`. So from the paper, the position `(j, k)` is referred to as super weight.

However if I set `W[j, k] = 0` but leave `y[0, j] = y_ref[0, j]` from the reference without pruning the super weight, I don't understand how this is any different than running the original model, as the output activation is then not changed at all?

However the paper seems to refer to this as "restoring super activation". So I am a bit confused here. Do you have more details?

Thank you!

**Comment by fxmarty-amd** [comment]
Relevant code is at https://github.com/mengxiayu/LLMSuperWeight/blob/ae1904db286e2ebca636ef79a7302dfe5845bf43/outliers/model.py#L312-L332 - the answer might be there

**Comment by mengxiayu** [comment]
> However if I set W[j, k] = 0 but leave y[1, j] = y_ref[1, j] from the reference without pruning the super weight, I don't understand how this is any different than running the original model, as the output activation is then not changed at all?

Some inaccuracies here. If we set W[j, k] = 0, not only y[1, j] changes, but also the j channel of all tokens, i.e.g,  y[:, j], change. Restoring SA is on one token, e.g., y[i, j], but leaving other tokens affected by pruning SW.

Yes, the code you found is correct.

**Comment by fxmarty-amd** [comment]
Thank you @mengxiayu, so I was specifically thinking about the decoding case where, for batch size = 1, the number of tokens is generally 1 (without speculative decoding).

So the "restoring super activation" case only make sense either at prefill and/or generally when multiple tokens are processed.
