### ISSUE TITLE
Plan for releasing code for identifying super weights

### ISSUE THREAD

**Issue by jeeyung** [mengxiayu/LLMSuperWeight#5]
Hello,

Thank you for sharing great work!

I was wondering if you have a plan to release the codes to detect super weights. Maybe `scripts/table2_find_superweight.sh` is going to be updated soon?

**Comment by mengxiayu** [comment]
Sorry for the confusion. Please refer to the code here: [scripts/figure3_how_to_identify_superweight.sh](https://github.com/mengxiayu/LLMSuperWeight/blob/main/scripts/figure3_how_to_identify_superweight.sh)
